### PR TITLE
Fix up DateTime support for seed bulkinsert().

### LINKED ISSUE #836: Seed issue with DateTime
I have a

    UsersSeed extends BaseSeed

with saving some rows that also include DateTime objects for created/modified.

When using Cake\I18n\DateTime objects, it fails with
```
[Cake\Database\Exception\QueryException] SQLSTATE[22007]: 
Invalid datetime format: 1292 Incorrect datetime value: '2025/04/07, 22:51' for column `ww_tmp`.`users`.`created` at row 1
Query: INSERT INTO `users` (`first_name`, `last_name`, `email`, `role`, `password`, `created`, `modified`) VALUES ('Admin', 'Tester', 'admin@example.com', 'admin', '$2y$10$SKxo0tPfZOMmlzLkrK3jIeoQbvo3S4L6INCxbTQTUFAe/8NeTd272', '2025/04/07, 22:51', '2025/04/07, 22:51'),('Manager', 'Tester', 'manager@example.com', 'manager', '$2y$10$NVzpBo6JUfX/hJXKpMMmP.BQVPPsUFg6lsRj9sQ9/8AwGZECY8hLG', '2025/04/07, 22:51', '2025/04/07, 22:51'),('User', 'Tester', 'user@example.com', 'user', '$2y$10$BFjYYQvYvlyssLWOkdfBPuC.7N4PPxHhV07FL2FjBz7pNB.EBqEBW', '2025/04/07, 22:51', '2025/04/07, 22:51') in /shared/httpd/ww/vendor/cakephp/cakephp/src/Database/Driver.php on line 382

Stack Trace:

Cake\Database\Driver->createQueryException() - CORE/src/Database/Driver.php, line 329
Cake\Database\Driver->executeStatement() - CORE/src/Database/Driver.php, line 295
Cake\Database\Driver->execute() - CORE/src/Database/Connection.php, line 268
Cake\Database\Connection->Cake\Database\{closure}() - CORE/src/Core/Retry/CommandRetry.php, line 71
Cake\Core\Retry\CommandRetry->run() - CORE/src/Database/Connection.php, line 268
Cake\Database\Connection->execute() - ROOT/vendor/cakephp/migrations/src/Db/Adapter/AbstractAdapter.php, line 733
Migrations\Db\Adapter\AbstractAdapter->bulkinsert() - ROOT/vendor/cakephp/migrations/src/Db/Adapter/AdapterWrapper.php, line 149
Migrations\Db\Adapter\AdapterWrapper->bulkinsert() - ROOT/vendor/cakephp/migrations/src/Db/Adapter/TimedOutputAdapter.php, line 101
Migrations\Db\Adapter\TimedOutputAdapter->bulkinsert() - ROOT/vendor/cakephp/migrations/src/Db/Table.php, line 803
Migrations\Db\Table->saveData() - ROOT/vendor/cakephp/migrations/src/Db/Table.php, line 775
Migrations\Db\Table->update() - ROOT/vendor/cakephp/migrations/src/Db/Table.php, line 833
Migrations\Db\Table->save() - ROOT/config/Seeds/UsersSeed.php, line 26
UsersSeed->run() - ROOT/vendor/cakephp/migrations/src/Migration/Environment.php, line 158
Migrations\Migration\Environment->executeSeed() - ROOT/vendor/cakephp/migrations/src/Migration/Manager.php, line 502
Migrations\Migration\Manager->executeSeed() - ROOT/vendor/cakephp/migrations/src/Migration/Manager.php, line 692
Migrations\Migration\Manager->seed() - ROOT/vendor/cakephp/migrations/src/Command/SeedCommand.php, line 124
Migrations\Command\SeedCommand->executeSeeds() - ROOT/vendor/cakephp/migrations/src/Command/SeedCommand.php, line 92
Migrations\Command\SeedCommand->execute() - CORE/src/Console/BaseCommand.php, line 202
Cake\Console\BaseCommand->run() - CORE/src/Console/CommandRunner.php, line 330
Cake\Console\CommandRunner->runCommand() - CORE/src/Console/CommandRunner.php, line 168
Cake\Console\CommandRunner->run() - ROOT/bin/cake.php, line 10
[main] - [main], line 0
```

I have to do this for each seed now, which is super annoying:
```php
        foreach ($data as &$row) {
            $row['created'] = $row['created']->toDateTimeString();
            $row['modified'] = $row['modified']->toDateTimeString();
        }
```

The same original data array works for Fixture set up though, so this is unique to the low level layer of Migrations and seeding it seems.

I assume it doesnt use the object correctly and uses a string representation which isnt set to ISO norm but normal output.
It should use the same toISO.. instead.

### PR DESCRIPTION
**Pull request by dereuromark**
Resolves https://github.com/cakephp/migrations/issues/836

Apparently adding this to bulkinsert()
```php
                    if ($placeholder == '?') {
                        if ($v instanceof DateTime) {
                            $vals[] = $v->toDateTimeString();
                        } elseif ($v instanceof Date) {
                            $vals[] = $v->toDateString();
                        } elseif (is_bool($v)) {
                            $vals[] = $this->castToBool($v);
                        } else {
                            $vals[] = $v;
                        }
                    }
```          
seems to fix it for my local MySql env.

How could a test case look like for this?
And in what class, for what method?

### CODE REVIEW

**Comment by markstory** [comment]
> How could a test case look like for this?

There are a few tests for bulkinsert already, there could be a new test for bulkinsert with datetime values. Most of the tests we have for bulkinsert are in each driver implementation though.

> And in what class, for what method?

You could include a seed integration test. There are a few integration tests for `bin/cake migrations seed` and we could have another one that inserts into a table with datetime columns.

**Comment by dereuromark** [comment]
Hm its all super confusing as long as we didnt major and get rid of the overhead of two systems under the hood.
Current seeds in testapp still

    extends AbstractSeed

So I assume this is part why for tests they dont run into the code above.
Also, once I add a local DateTime::setToStringFormat() it also seems to cause issues.

I might need some help to get this covered.

In real prod env the above fix works fine (using BaseSeed ext) and saves DateTime properly now.

**Comment by dereuromark** [comment]
I removed the changes again, the tests still pass.
But locally, on my system, it does not pass for actual DB columns.

**Comment by dereuromark** [comment]
Hah now I can reproduce also in CI :)
But it seems for test run it does not make a difference, it skips this adapter and seems to use its own one.

File: tests/TestCase/Command/Phinx/SeedTest.php [hunk 1]
```diff
@@ -133,6 +136,88 @@ public function testExecute()
         $migrations->rollback(['target' => 'all']);
     }
 
+    /**
+     * Test executing the "seed" command with bulkinsert and timestamps
+     *
+     * @return void
+     */
+    public function testExecuteTimestampFields()
```
Comment (markstory) [inline tests/TestCase/Command/Phinx/SeedTest.php]: Did you mean to add this test to the phinx based seed command? Adding tests to `tests/TestCase/Command/SeedCommandTest.php` would be preferable.

Comment (dereuromark) [reply tests/TestCase/Command/Phinx/SeedTest.php]: there were some tests already in here, but sure we could move them.

Comment (markstory) [reply tests/TestCase/Command/Phinx/SeedTest.php]: The adapter you've changed isn't used when migrations uses the `phinx` backend which these command tests use.

**Comment by dereuromark** [comment]
@markstory Thanks a lot for the help
It indeed only gets triggered throw this part of the system

I was finally able to get it reproduced for Mysql both locally and on CI, and was able to show now that the fix indeed is helping.

**Comment by dereuromark** [comment]
The remaining error seems to be dependant on a fix in Phinx directly maybe?
https://github.com/cakephp/phinx/pull/2348

The rest seems now green instead of red :)

**Comment by dereuromark** [comment]
All fixed, and the phinx one should be merged soon.

PS: Lets please squash merge this one.

**Comment by dereuromark** [comment]
https://github.com/cakephp/phinx/releases/tag/0.16.7
has been released

I squashed

**Comment by dereuromark** [comment]
@markstory 
The remaining fails:
https://github.com/cakephp/migrations/actions/runs/14521746190/job/40744069928?pr=838
Are those on phinx or us?

**Comment by markstory** [comment]
> 4) Migrations\Test\TestCase\MigrationsTest::testSeed with data set #0 ('builtin')
> Cake\Database\Exception\QueryException: SQLSTATE[22007]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The conversion of a nvarchar data type to a datetime data type resulted in an out-of-range value.
Query: INSERT INTO [dbo].[stores] ([name], [created], [modified]) VALUES ('foo', '4/17/25', '4/17/25'),('foo_with_date', '4/17/25, 5:55 PM', '4/17/25, 5:55 PM')

It looks like there are still some issues with datetimes being cast to the wrong string format. This could be a migrations issue. There was a specialized `bulkinsert` implementation added in #826

**Comment by dereuromark** [comment]
Thx, I think I finally got it.

The remaining fail is already on 4.x and due to the fact that we support still cake5.0, and we probably need a version switch on those tests.

**Comment by markstory** [comment]
> The remaining fail is already on 4.x and due to the fact that we support still cake5.0, and we probably need a version switch on those tests.

I have to bump the dev dependency to not use 5.x-dev.
