### PR TITLE
Using our own adapter to avoid issues with transactions.

### LINKED ISSUE #83: Migration Seed for Postgres driver was get PDO Error (There is no active transaction for seed data)
I'm trying to create seed data from CakePHP 3 migration file, with Postgres as database driver. But i have got error message under console after run:

```php
bin/cake migrations migrate
```

PDOException: There is no active transaction

Here are my code:

```php
<?php
use Phinx\Migration\AbstractMigration;
use Cake\ORM\TableRegistry;
use Cake\Utility\Security;

class CreateSeedUsers extends AbstractMigration
{
    /**
     * Migrate Up.
     */
    public function up()
    {
        $modelName = 'Users';
        
        $data = [
            [
                'username' => 'admin', 
                'email' => 'admin@demo.com', 
                'password' => Security::hash('123', 'sha1', true)
            ], 
            [
                'username' => 'seller', 
                'email' => 'seller@demo.com', 
                'password' => Security::hash('123', 'sha1', true)
            ], 
            [
                'username' => 'member', 
                'email' => 'member@demo.com', 
                'password' => Security::hash('123', 'sha1', true)
            ]
        ];
        
        $table = TableRegistry::get($modelName);
        $entities = $table->newEntities($data);
        
        // In a controller.
        foreach ($entities as $entity) {
            // Save entity
            $table->save($entity);
        }   
    }

    /**
     * Migrate Down.
     */
    public function down()
    {
        if ($this->query("TRUNCATE users")) {
            echo " > Table has been initialized\n\n";
        } 
        else 
        {
            echo " > Warning, table failed to initialized!!!\n\n";
        }
    }
}

```

If i use mysql as database driver, its working good.

Someone please help me. Thank you.

### PR DESCRIPTION
**Pull request by lorenzo**
Also aliasing the 'default' connection so that seeding databases can work
more seamlessly.

Fixes #83

### CODE REVIEW

File: src/CakeAdapter.php [hunk 1]
```diff
@@ -0,0 +1,574 @@
...
+    }
+
+    /**
+     * Does the adapter support transactions?
+     *
+     * @return boolean
+     */
+    public function hasTransactions()
+    {
+        return $this->_adapter->hasTransactions();
```
Comment (markstory) [inline src/CakeAdapter.php]: Should this use the connection methods instead?

File: src/ConfigurationTrait.php [hunk 2]
```diff
@@ -166,9 +166,15 @@ public function setInput(InputInterface $input)
     public function bootstrap(InputInterface $input, OutputInterface $output)
     {
         parent::bootstrap($input, $output);
-        $connection = ConnectionManager::get($this->getConnectionName($input));
-        $pdo = $this->getManager()->getEnvironment('default')->getAdapter()->getConnection();
-        $connection->driver()->connection($pdo);
+        $name = $this->getConnectionName($input);
+        ConnectionManager::alias($name, 'default');
+        $connection = ConnectionManager::get($name);
```
Comment (markstory) [inline src/ConfigurationTrait.php]: What is the alias for?

File: src/CakeAdapter.php (hunk 1 above)
Comment (lorenzo) [inline src/CakeAdapter.php]: No, this means whether or not the adapter supports transactions. We don't really have a method for that

File: src/ConfigurationTrait.php (hunk 2 above)
Comment (lorenzo) [inline src/ConfigurationTrait.php]: If you invoke the migrations shell passing a custom connection argument, you would expect that using any table class would automatically default to that custom connection instead of another.

File: src/CakeAdapter.php (hunk 1 above)
Comment (markstory) [inline src/CakeAdapter.php]: Ah ok. I thought it checked if there were open transactions.

File: src/ConfigurationTrait.php (hunk 2 above)
Comment (markstory) [inline src/ConfigurationTrait.php]: Ok.

**Comment by HavokInspiration** [comment]
Looks good to me.
I'll try to pull this tonight and run some tests on my dev setup to see if this is working okay.

**Comment by HavokInspiration** [comment]
Everything works fine on my side both with MySQL and Postgres as well as both with the default or a custom connection.
Well done @lorenzo :clap:

**Comment by lorenzo** [comment]
Thanks for confirming, @HavokInspiration
