### PR TITLE
Fix snapshots for plugins.

### LINKED ISSUE #463: Unable to bake migrations migration_snapshot in the plugin using another connection
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.9.
* Migrations plugin version: ^3.0.
* Bake plugin version (if relevant): ^2.0.3.
* Database server (MySQL, SQLite, Postgres): MariaDB 10.4
* PHP Version: 7.3
* Platform / OS: Debian (VagrantBox debian/contrib-stretch64)

###  I try to bake migrations migration_snapshot in the plugin using another connection
* Have two db on same server and setup in app.php (default, forum)
* I can bake migrations snapshot or diff for both connection in main migrations folder, example
`bin/cake bake migration_snapshot Forum --connection forum`

* But if I try to bake migrations snapshot or diff in plugin (backed forum plugin) with 'forum' connection, then bake create migrations file with empty up and down methods

`bin/cake bake migration_snapshot Forum --plugin Forum --connection forum` 

```
<?php
declare(strict_types=1);

use Migrations\AbstractMigration;

class Forum extends AbstractMigration
{
    /**
     * Up Method.
     * ...
     */
    public function up()
    {
    }

    /**
     * Down Method.
     * ...
    */
    public function down()
    {
    }
}
```

### PR DESCRIPTION
**Pull request by dereuromark**
Resolves https://github.com/cakephp/migrations/issues/463

  Root Cause

  The bug was in src/Util/TableFinder.php:72. The code incorrectly treated the --plugin option the same as --require-table, filtering tables to only include those with corresponding Table classes in the plugin. When creating
   an initial migration snapshot for a plugin (before Table classes exist), this resulted in an empty migration.

  The Fix

  Changed line 72 in src/Util/TableFinder.php:
  ```
  // Before (buggy)
  if ($options['require-table'] === true || $options['plugin']) {

  // After (fixed)  
  if ($options['require-table'] === true) {
  ```
  Behavior Changes

  Before:
  - --plugin option would filter tables to only include those with Table classes in the plugin
  - Made it impossible to create initial snapshots for plugins with custom connections

  After:
  - --plugin option only determines where the migration file is saved
  - All tables from the specified connection are included (excluding phinxlog tables)
  - Use --require-table if you want to filter by existing Table classes

### CODE REVIEW

File: tests/comparisons/Migration/pgsql/test_snapshot_plugin_blog_pgsql.php [hunk 1]
```diff
@@ -117,6 +168,143 @@ public function up(): void
...
+                    ->setName('products_slug_unique')
+                    ->setType('unique')
+            )
+            ->addIndex(
+                $this->index('title')
+                    ->setName('products_title_idx')
+            )
+            ->create();
+
+        $this->table('special_pks', ['id' => false, 'primary_key' => ['id']])
```
Comment (markstory) [inline tests/comparisons/Migration/pgsql/test_snapshot_plugin_blog_pgsql.php:220]: Is this the expected behavior now? Generating a migration for a plugin without `--require-table` will include _every_ table in the database?

Comment (dereuromark) [reply tests/comparisons/Migration/pgsql/test_snapshot_plugin_blog_pgsql.php:220]: Check the initial report. I think it does make sense as outlined above, since otherwise you couldnt use it for plugins initially at all.

Comment (markstory) [reply tests/comparisons/Migration/pgsql/test_snapshot_plugin_blog_pgsql.php:220]: The original issue doesn't make it clear if the model classes existed or not. I have to assume that the model classes don't exist.

Having the plugin option only change the output directory fits with how other bake tasks work as well.
